name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Run tests
      run: |
        cd server
        make test

    - name: Build binaries
      run: |
        cd server
        mkdir -p bin

        # Build for multiple architectures
        GOOS=linux GOARCH=amd64 go build -o bin/zoteroflow2-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o bin/zoteroflow2-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -o bin/zoteroflow2-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o bin/zoteroflow2-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -o bin/zoteroflow2-windows-amd64.exe .

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ZoteroFlow2 ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./server/bin/zoteroflow2-linux-amd64
        asset_name: zoteroflow2-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Assets (Darwin AMD64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./server/bin/zoteroflow2-darwin-amd64
        asset_name: zoteroflow2-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Assets (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./server/bin/zoteroflow2-windows-amd64.exe
        asset_name: zoteroflow2-windows-amd64.exe
        asset_content_type: application/octet-stream