name: Security Scan (Fixed)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 每周一UTC 00:00运行安全扫描
    - cron: '0 0 * * 1'

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25

    - name: Run Gosec Security Scanner
      uses: securecodewarrior/github-action-gosec@v5
      with:
        args: '-no-fail -fmt sarif -out results.sarif ./...'
        working-directory: server

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: server/results.sarif

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'server'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run govulncheck
      run: |
        cd server
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...

    - name: Check for known vulnerabilities
      run: |
        cd server
        go list -m -u all | grep -E "(CVE|vulnerability)" || echo "✅ No known vulnerabilities found"